FROM node:20.11-buster-slim as node

RUN apt-get update -qq && apt-get install -y xdg-utils
RUN yarn add vite@latest -g
COPY ./package.json package.json
COPY ./yarn.lock yarn.lock

WORKDIR /app
EXPOSE 5173
CMD ["yarn", "run", "dev", "--host"]